# # Create a list of strings: mutants
# mutants = ['charles xavier',  'bobby drake', 'kurt wagner',  'max eisenhardt',  'kitty pryde']
#
# mutant_list = list(enumerate(mutants))
# print(mutant_list)
#
# for index1, value1 in enumerate(mutants):
#     print(index1, value1, end= ' ')
#
# for index2, value2 in enumerate(mutants, start=1):
#     print(index2, value2)

# -----------------------------------------------------------------------------------------------------------------------------------

# mutant_data = list(zip(mutants, aliases, powers))
# print(mutant_data)
#
# mutant_zip = zip(mutants, aliases, powers)
# print(mutant_zip)
#
# for value1, value2, value3  in mutant_zip:
#     print(value1, value2, value3)

# -----------------------------------------------------------------------------------------------------------------------------------

# mutants = ['Charles xavier', 'bobby drake', 'kurt wanger', 'max eisenhardt', 'kitty prayde']
# powers = ['telepathy', 'thermokinesis', 'teleportation', 'magnetokinesis', 'intangibility']
# z1 = zip(mutants, powers)
# print(*z1)
#
# z1 = zip(mutants, powers)
# result1, result2 = zip(*z1)
#
# print(result1 == mutants)
# print(result2 == powers)

# --------------------------------------------------------------------------------------------------------------

# fellowship = ['frodo', 'samwise', 'merry', 'aragorn', 'legolas', 'boromir', 'gimli']
# new_fellowship = [member if len(member) >= 7 else member.replace(member, '') for member in fellowship]
# dic_fellowship = {member:len(member) for member in fellowship}
#
# print(dic_fellowship)
# print(new_fellowship)

# --------------------------------------------------------------------------------------------------------------
# Create generator object: result
# result = (num for num in range(0, 31))
#
# print(next(result))
# print(next(result))
# print(next(result))
# print(next(result))
# print(next(result))
#
# # Print the rest of the values
# for value in result:
#     print(value)

# --------------------------------------------------------------------------------------------------------------

# Create a list of strings
# lannister = ['cersei', 'jaime', 'tywin', 'tyrion', 'joffrey']
#
#
# # Define generator function get_lengths
# def get_lengths(input_list):
#     for person in input_list:
#         yield len(person)
#
#
# # Print the values generated by get_lengths()
# for value in get_lengths(lannister):
#     print(value)

