udemy:
  email: "abu35-1994@diu.edu.bd" # Enter your Udemy registered email here
  password: "AbuBakkar32" # Enter your Udemy password here
  zipcode: "1207" # If Udemy requires a zipcode for your country, enter it here.